/*
 Generated by typeshare 1.13.4
*/

/**
 * Inherited type for all objects.
 * 
 * This includes everything from aircrafts, ground units, to any point in space that can be tracked
 */
export type Object = number;

/** Inherited type for all tasks */
export type Task = number;

/** Designation of object */
export enum ObjectDesignation {
	UNKNOWN = "UNKNOWN",
	HOSTILE = "HOSTILE",
	CIVILIAN = "CIVILIAN",
	ALLY = "ALLY",
	FRIENDLY = "FRIENDLY",
}

