pub mod simulation {
    // Includes the code generated by prost-build
    include!("../generated/simulation.rs");
}

use simulation::{Object, Task};
use ulid::Ulid;

/// Extension trait to provide seamless ULID support for Protobuf messages.
///
/// Since Protobuf 'bytes' map to `Vec<u8>`, this trait handles the
/// conversion to and from the fixed 16-byte array required by ULIDs.
pub trait UlidSupport {
    /// Retrieves the ID as a native Ulid type.
    fn get_ulid(&self) -> Ulid;
    /// Sets the ID using a native Ulid type.
    fn set_ulid(&mut self, id: Ulid);
}

impl UlidSupport for Object {
    fn get_ulid(&self) -> Ulid {
        // Safely attempt to convert Vec<u8> to [u8; 16]
        let bytes: [u8; 16] = self.object_id.as_slice().try_into().unwrap_or([0; 16]);
        Ulid::from_bytes(bytes)
    }

    fn set_ulid(&mut self, id: Ulid) {
        self.object_id = id.to_bytes().to_vec();
    }
}

impl UlidSupport for Task {
    fn get_ulid(&self) -> Ulid {
        let bytes: [u8; 16] = self.task_id.as_slice().try_into().unwrap_or([0; 16]);
        Ulid::from_bytes(bytes)
    }

    fn set_ulid(&mut self, id: Ulid) {
        self.task_id = id.to_bytes().to_vec();
    }
}
